// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Projet UNIFIÉ : velox-pro-d6030 (app Android : dj.velox.client)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWgVLKrP4KdC3rjwSUUdzdVWsQZarloU',
    appId: '1:23290944403:android:2786762ed63b5ac9a9a666',
    messagingSenderId: '23290944403',
    projectId: 'velox-pro-d6030',
    storageBucket: 'velox-pro-d6030.firebasestorage.app',
  );

  // iOS : à reconfigurer via `flutterfire configure` quand tu enregistreras
  // l'app iOS dans velox-pro-d6030. Pour l'instant, projet pointé sur velox-pro
  // (l'app n'est pas compilée pour iOS, donc ce bloc n'est pas utilisé).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuWgVLKrP4KdC3rjwSUUdzdVWsQZarloU',
    appId: '1:23290944403:android:2786762ed63b5ac9a9a666',
    messagingSenderId: '23290944403',
    projectId: 'velox-pro-d6030',
    storageBucket: 'velox-pro-d6030.firebasestorage.app',
    iosBundleId: 'dj.velox.client',
  );
}
